# Site settings
title: Mylium
email: info@mylium.eu
description: >  # this means to ignore newlines until "baseurl:"
 FPGA solutions
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.mylium.eu" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
